services:
  # Optional: Auto-update dreamscribe to the latest image from GHCR in dev mode
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Poll every 5 minutes and clean up old images, only update the 'dreamscribe' container
    command: --interval 300 --cleanup dreamscribe
