server:
  host: "0.0.0.0"
  port: "8080"
pcas:
  address: "localhost:50051"
  eventType: "capability.streaming.transcribe.v1"
  translateEventType: "capability.streaming.translate.v1"
  summarizeEventType: "capability.streaming.summarize.v1"
  chatEventType: "capability.streaming.chat.v1"
user:
  id: "default-user"
